### ISSUE TITLE
运行代码中遇到了错误，想请教一下。

### ISSUE THREAD

**Issue by Gaoshuang77** [lpq29743/RAM#11]
因为300维的glove太大，我使用了glove.6B.100d.txt，并将main.py中embedding_dim和n_hidden改成了100，但是运行中遇到了报错。请问您知道如何解决？谢谢。
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 38, in main
    FLAGS.word2vec = load_word_embeddings(FLAGS.embedding_fname, FLAGS.embedding_dim, FLAGS.word2id)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 499, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 375, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'word2vec'

**Comment by Gaoshuang77** [comment]
我在添加上这个命令行标志后解决了 谢谢。
